name: Build
on:
  push:
    branches: [ tempdev ]
  pull_request:
    branches: [ main ]

jobs:
  run-builds:
    strategy:
      matrix:
        project: [TrfrtSbmt.Api, TrfrtSbmt.Cdk, TrfrtSbmt.Tests, TrfrtSbmt.VoteStreamProcessor]
    uses: colinmxs/trfrt-sbmt-api/.github/workflows/build.yml@tempdev
    with:
      project: ${{ matrix.project }}
  #build-and-deploy:
  #  runs-on: self-hosted
  #  steps:
  #  - uses: actions/checkout@v3    
    #- name: Replace tokens
    #  uses: cschleiden/replace-tokens@v1.1
    #  with:
    #    tokenPrefix: '#{'
    #    tokenSuffix: '}#'
    #    files: '**/*/*.json'
    #  env:
    #    ACCOUNTID: ${{ secrets.AWS_ACCOUNT_ID }}
    #    USWEST1SSLCERTID: ${{ secrets.AWS_SSL_CERT_ID_US_WEST_1 }}
    #    USWEST2SSLCERTID: ${{ secrets.AWS_SSL_CERT_ID_US_WEST_2 }}
    #    DOMAIN: ${{ secrets.DOMAIN }}
    #    SUBDOMAIN: ${{ secrets.SUBDOMAIN }}
    #    DISCORDWEBHOOKURL: ${{ secrets.DISCORD_WEBHOOK_URL}}
    #    ASPNETENVIRONMENT: Development
    #- name: Run Tests
    #  run: |
    #    dotnet test TrfrtSbmt.Tests    
    #- name: Deploy
    #  run: |      
    #    cd TrfrtSbmt.Cdk/bin/Release/net6.0
    #    cdk deploy * --require-approval never
    #    #cdk diff *
