name: build
on:
  workflow_call:
    inputs:
      project:
        type: string
        required: true
jobs:
  build:
    runs-on: 'self-hosted'
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          dotnet publish ${{ inputs.project }}/${{ inputs.project }}.csproj --configuration Release
      - name: Upload Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: ${{ inputs.project }}
          path: ${{ inputs.project }}/bin/Release/net6.0/publish
          retention-days: 1          