name: Regional Api Pipeline
on:
  push:
    branches: [ tempdev ]
  pull_request:
    branches: [ main ]

jobs:
  #run-tests:
  #  runs-on: self-hosted    
  #  steps:    
  #  - name: Run Tests
  #    run: |
  #      dotnet test TrfrtSbmt.Tests
  build-assets:
    uses: colinmxs/trfrt-sbmt-api/.github/workflows/build-assets.yml@tempdev  
  deploy:
    needs: [ build-assets ]        
    strategy:
      matrix:
        env: [ Development ]
    uses: colinmxs/trfrt-sbmt-api/.github/workflows/deploy-jobs.yml@tempdev
    with:
      env: ${{ matrix.env }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_SSL_CERT_ID_US_WEST_1: ${{ secrets.AWS_SSL_CERT_ID_US_WEST_1 }}
      AWS_SSL_CERT_ID_US_WEST_2: ${{ secrets.AWS_SSL_CERT_ID_US_WEST_2 }}
      AWS_SSL_CERT_ID_GLOBAL: ${{ secrets.AWS_SSL_CERT_ID_GLOBAL }}
      DOMAIN: ${{ secrets.DOMAIN }}
      SUBDOMAIN: ${{ secrets.SUBDOMAIN }}
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL}}
