name: Regional Api Pipeline
on:
  push:
    branches: [ tempdev ]
  pull_request:
    branches: [ main ]

jobs:
  build-assets:
    uses: colinmxs/trfrt-sbmt-api/.github/workflows/build-assets.yml@tempdev
  run-tests:
    needs: build-assets
    runs-on: self-hosted    
    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v3
      with:
        name: TrfrtSbmt.Tests
    - name: Run Tests
      run: |
        dir
        dotnet test --no-build TrfrtSbmt.Tests
  deploy:
    needs: run-tests        
    strategy:
      matrix:
        env: [ Development ]
    uses: colinmxs/trfrt-sbmt-api/.github/workflows/deploy-jobs.yml@tempdev
    with:
      env: ${{ matrix.env }}
