name: Build
on:
  push:
    branches: [ tempdev ]
  pull_request:
    branches: [ main ]

jobs:
  build-assets:
    uses: colinmxs/trfrt-sbmt-api/.github/workflows/build-assets.yml@tempdev
  run-tests:
    needs: build-assets
    runs-on: self-hosted    
    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v3
      with:
        name: TrfrtSbmt.Tests
    - name: Run Tests
      run: |
        dotnet test TrfrtSbmt.Tests
  deploy:
    needs: run-tests
    runs-on: self-hosted
    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v3
    - name: Replace tokens
      uses: cschleiden/replace-tokens@v1.1
      with:
        tokenPrefix: '#{'
        tokenSuffix: '}#'
        files: '**/*/*.json'
      env:
        ACCOUNTID: ${{ secrets.AWS_ACCOUNT_ID }}
        USWEST1SSLCERTID: ${{ secrets.AWS_SSL_CERT_ID_US_WEST_1 }}
        USWEST2SSLCERTID: ${{ secrets.AWS_SSL_CERT_ID_US_WEST_2 }}
        DOMAIN: ${{ secrets.DOMAIN }}
        SUBDOMAIN: ${{ secrets.SUBDOMAIN }}
        DISCORDWEBHOOKURL: ${{ secrets.DISCORD_WEBHOOK_URL}}
        ASPNETENVIRONMENT: Development    
    - name: Deploy
      run: |      
        cd TrfrtSbmt.Cdk
        #cdk deploy * --require-approval never
        cdk diff *