name: build
on:
  workflow_call:
jobs:
  reusable_workflow_job:
	runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Bootstrap CDK
      run: |
        cdk bootstrap aws://${{ secrets.AWS_ACCOUNT_ID }}/us-west-1
        cdk bootstrap aws://${{ secrets.AWS_ACCOUNT_ID }}/us-west-2
