name: deploy-jobs
on:
  workflow_call:
    inputs:
      env:
        type: string
        required: true
      github_env:
        type: string
        required: true
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout    
jobs:
  deploy:    
    runs-on: self-hosted
    environment: ${{ inputs.github_env }}
    steps:    
    - name: Download Artifacts
      uses: actions/download-artifact@v4.1.7    
    - name: Replace tokens
      uses: cschleiden/replace-tokens@v1.1
      with:
        tokenPrefix: '#{'
        tokenSuffix: '}#'
        files: '**/*/*.json'
      env:
        ACCOUNTID: ${{ secrets.AWS_ACCOUNT_ID }}
        USWEST1SSLCERTID: ${{ secrets.AWS_SSL_CERT_ID_US_WEST_1 }}
        USWEST2SSLCERTID: ${{ secrets.AWS_SSL_CERT_ID_US_WEST_2 }}
        GLOBALSSLCERTID: ${{ secrets.AWS_SSL_CERT_ID_GLOBAL }}
        DOMAIN: ${{ secrets.DOMAIN }}
        SUBDOMAIN: ${{ secrets.SUBDOMAIN }}
        DISCORDWEBHOOKURL: ${{ secrets.DISCORD_WEBHOOK_URL}}
        ASPNETENVIRONMENT: ${{ inputs.env}}   
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v1.7.0
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubAction-AssumeRoleWithAction
        role-session-name: GitHub_to_AWS_via_FederatedOIDC
        aws-region: us-west-2
    - name: Deploy Oregon
      run: |      
        cd trfrt-sbmt/TrfrtSbmt.Cdk
        cdk deploy TrfrtSbmt-ApiStack-us-west-2-${{ inputs.env}} --require-approval never
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v1.7.0
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubAction-AssumeRoleWithAction
        role-session-name: GitHub_to_AWS_via_FederatedOIDC
        aws-region: us-west-1
    - name: Deploy California
      run: |      
        cd trfrt-sbmt/TrfrtSbmt.Cdk
        cdk deploy TrfrtSbmt-ApiStack-us-west-1-${{ inputs.env}} --require-approval never
  