name: deploy-jobs
on:
  workflow_call:
    inputs:
      env:
        type: string
        required: true
    
jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v3
    - name: Unzip Artifacts
      run: |
        Expand-Archive -LiteralPath "C:\actions-runner-1\_work\trfrt-sbmt-api\trfrt-sbmt-api\trfrt-sbmt.zip" -Destination _artifacts
    - name: Replace tokens
      uses: cschleiden/replace-tokens@v1.1
      with:
        tokenPrefix: '#{'
        tokenSuffix: '}#'
        files: '**/*/*.json'
      env:
        ACCOUNTID: ${{ secrets.AWS_ACCOUNT_ID }}
        USWEST1SSLCERTID: ${{ secrets.AWS_SSL_CERT_ID_US_WEST_1 }}
        USWEST2SSLCERTID: ${{ secrets.AWS_SSL_CERT_ID_US_WEST_2 }}
        GLOBALSSLCERTID: ${{ secrets.AWS_SSL_CERT_ID_GLOBAL }}
        DOMAIN: ${{ secrets.DOMAIN }}
        SUBDOMAIN: ${{ secrets.SUBDOMAIN }}
        DISCORDWEBHOOKURL: ${{ secrets.DISCORD_WEBHOOK_URL}}
        ASPNETENVIRONMENT: ${{ inputs.env}}    
    - name: Deploy Oregon
      run: |      
        cd TrfrtSbmt.Cdk
        cdk deploy TrfrtSbmt-ApiStack-us-west-2-${{ inputs.env}} --require-approval never
    - name: Deploy California
      run: |      
        cd TrfrtSbmt.Cdk
        cdk deploy TrfrtSbmt-ApiStack-us-west-1-${{ inputs.env}} --require-approval never
  