name: deploy-jobs
on:
  workflow_call:
    inputs:
      env:
        type: string
        required: true
    secrets:
      AWS_ACCOUNT_ID:
        required: true
      AWS_SSL_CERT_ID_US_WEST_1:
        required: true
      AWS_SSL_CERT_ID_US_WEST_2:
        required: true
      AWS_SSL_CERT_ID_US_GLOBAL:
        required: true
      DOMAIN:
        required: true
      SUBDOMAIN:
        required: true
      DISCORD_WEBHOOK_URL:
        required: true
jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v3
    - name: Replace tokens
      uses: cschleiden/replace-tokens@v1.1
      with:
        tokenPrefix: '#{'
        tokenSuffix: '}#'
        files: '**/*/*.json'
      env:
        ACCOUNTID: ${{ secrets.AWS_ACCOUNT_ID }}
        USWEST1SSLCERTID: ${{ secrets.AWS_SSL_CERT_ID_US_WEST_1 }}
        USWEST2SSLCERTID: ${{ secrets.AWS_SSL_CERT_ID_US_WEST_2 }}
        GLOBALSSLCERTID: ${{ secrets.AWS_SSL_CERT_ID_GLOBAL }}
        DOMAIN: ${{ secrets.DOMAIN }}
        SUBDOMAIN: ${{ secrets.SUBDOMAIN }}
        DISCORDWEBHOOKURL: ${{ secrets.DISCORD_WEBHOOK_URL}}
        ASPNETENVIRONMENT: ${{ inputs.env}}    
    - name: Deploy
      run: |      
        cd TrfrtSbmt.Cdk
        #cdk deploy * --require-approval never
        cdk diff *
  